
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[[constraint]]
  name = "github.com/cespare/xxhash"
  version = "1.0.0"

[[constraint]]
  name = "github.com/go-openapi/analysis"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/errors"
  version = "0.16.0"


[[constraint]]
  name = "github.com/go-openapi/jsonpointer"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/jsonreference"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/loads"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/runtime"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/spec"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/strfmt"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/swag"
  version = "0.16.0"

[[constraint]]
  name = "github.com/go-openapi/validate"
  version = "0.16.0"

[[constraint]]
  name = "github.com/gocql/gocql"
  source = "git@github.com:scylladb/gocql.git"
  version = "1.0.1"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/hailocab/go-hostpool"

[[constraint]]
  name = "github.com/scylladb/gocqlx"
  version = "1.2.1"

[[constraint]]
  name = "github.com/scylladb/go-set"
  version = "1.0.1"

[[constraint]]
  branch = "master"
  name = "github.com/scylladb/go-log"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.9.1"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.2"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.1.1"

[[constraint]]
  name = "github.com/google/gops"
  version = "0.3.2"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "0.2.3"

[prune]
  go-tests = true
  unused-packages = true
