services:
  dc1_node_1:
    image: scylladb/agent-${SCYLLA_VERSION}
    privileged: true
    volumes:
      - type: bind
        source: ./scylla/cassandra-rackdc.1.properties
        target: /etc/scylla/cassandra-rackdc.properties
      - type: bind
        source: ./scylla/scylla.yaml
        target: /etc/scylla/scylla.yaml
      - type: bind
        source: ./scylla/object_storage.yaml
        target: /etc/scylla/object_storage.yaml
      - type: bind
        source: ./scylla/certs/
        target: /etc/scylla/certs
    networks:
      public:
      second:

  dc1_node_2:
    image: scylladb/agent-${SCYLLA_VERSION}
    privileged: true
    volumes:
      - type: bind
        source: ./scylla/cassandra-rackdc.1.properties
        target: /etc/scylla/cassandra-rackdc.properties
      - type: bind
        source: ./scylla/scylla.yaml
        target: /etc/scylla/scylla.yaml
      - type: bind
        source: ./scylla/object_storage.yaml
        target: /etc/scylla/object_storage.yaml
      - type: bind
        source: ./scylla/certs/
        target: /etc/scylla/certs
    networks:
      public:
      second:

  dc1_node_3:
    image: scylladb/agent-${SCYLLA_VERSION}
    privileged: true
    volumes:
      - type: bind
        source: ./scylla/cassandra-rackdc.1.properties
        target: /etc/scylla/cassandra-rackdc.properties
      - type: bind
        source: ./scylla/scylla.yaml
        target: /etc/scylla/scylla.yaml
      - type: bind
        source: ./scylla/object_storage.yaml
        target: /etc/scylla/object_storage.yaml
      - type: bind
        source: ./scylla/certs/
        target: /etc/scylla/certs/
    networks:
      public:
      second:

  dc2_node_1:
    image: scylladb/agent-${SCYLLA_VERSION}
    privileged: true
    volumes:
      - type: bind
        source: ./scylla/cassandra-rackdc.2.properties
        target: /etc/scylla/cassandra-rackdc.properties
      - type: bind
        source: ./scylla/scylla.yaml
        target: /etc/scylla/scylla.yaml
      - type: bind
        source: ./scylla/object_storage.yaml
        target: /etc/scylla/object_storage.yaml
      - type: bind
        source: ./scylla/certs/
        target: /etc/scylla/certs
    networks:
      public:
      second:

  dc2_node_2:
    image: scylladb/agent-${SCYLLA_VERSION}
    privileged: true
    volumes:
      - type: bind
        source: ./scylla/cassandra-rackdc.2.properties
        target: /etc/scylla/cassandra-rackdc.properties
      - type: bind
        source: ./scylla/scylla.yaml
        target: /etc/scylla/scylla.yaml
      - type: bind
        source: ./scylla/object_storage.yaml
        target: /etc/scylla/object_storage.yaml
      - type: bind
        source: ./scylla/certs/
        target: /etc/scylla/certs
    networks:
      public:
      second:

  dc2_node_3:
    image: scylladb/agent-${SCYLLA_VERSION}
    privileged: true
    volumes:
      - type: bind
        source: ./scylla/cassandra-rackdc.2.properties
        target: /etc/scylla/cassandra-rackdc.properties
      - type: bind
        source: ./scylla/scylla.yaml
        target: /etc/scylla/scylla.yaml
      - type: bind
        source: ./scylla/object_storage.yaml
        target: /etc/scylla/object_storage.yaml
      - type: bind
        source: ./scylla/certs/
        target: /etc/scylla/certs
    networks:
      public:
      second:

  second_cluster_dc1_node_1:
    image: scylladb/agent-${SCYLLA_VERSION}
    privileged: true
    volumes:
      - type: bind
        source: ./scylla/cassandra-rackdc.1.properties
        target: /etc/scylla/cassandra-rackdc.properties
      - type: bind
        source: ./scylla/scylla-second-cluster.yaml
        target: /etc/scylla/scylla.yaml
      - type: bind
        source: ./scylla/object_storage.yaml
        target: /etc/scylla/object_storage.yaml
      - type: bind
        source: ./scylla/certs/
        target: /etc/scylla/certs
    networks:
      public:
      second:

  second_cluster_dc1_node_2:
    image: scylladb/agent-${SCYLLA_VERSION}
    privileged: true
    volumes:
      - type: bind
        source: ./scylla/cassandra-rackdc.1.properties
        target: /etc/scylla/cassandra-rackdc.properties
      - type: bind
        source: ./scylla/scylla-second-cluster.yaml
        target: /etc/scylla/scylla.yaml
      - type: bind
        source: ./scylla/object_storage.yaml
        target: /etc/scylla/object_storage.yaml
      - type: bind
        source: ./scylla/certs/
        target: /etc/scylla/certs
    networks:
      public:
      second:

  scylla-manager-db:
    image: scylladb/${SCYLLA_VERSION}
    ports:
      - "9042:9042"
      - "10000:10000"
    volumes:
      - type: bind
        source: ./scylla/cassandra-rackdc.1.properties
        target: /etc/scylla/cassandra-rackdc.properties
      - type: bind
        source: ./scylla/scylla-sm.yaml
        target: /etc/scylla/scylla.yaml
    networks:
      second:

  minio:
    image: minio/minio:${MINIO_VERSION}
    privileged: true
    user: ${CURRENT_UID}:${CURRENT_GID}
    command: server /data --console-address ":9001" --certs-dir=/.minio
    environment:
      MINIO_REGION: ${MINIO_REGION}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - type: bind
        source: ${MINIO_DATA_DIR}
        target: /data
      - type: bind
        source: ${MINIO_CERT_DIR}
        target: /.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      second:

  prometheus:
    image: prom/prometheus:${PROMETHEUS_VERSION}
    ports:
      - "9090:9090"
    networks:
      second:

networks:
  public:
    driver: bridge
    ipam:
      driver: default
  second:
    driver: bridge
    ipam:
      driver: default
