version: "3.7"

services:
  dc1_node_1:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    privileged: true
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - type: bind
        source: ./scylla/cassandra-rackdc.1.properties
        target: /etc/scylla/cassandra-rackdc.properties
      - type: bind
        source: ./scylla/scylla.yaml
        target: /etc/scylla/scylla.yaml
    networks:
      public:
        ipv4_address: 192.168.100.11

  dc1_node_2:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    privileged: true
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - type: bind
        source: ./scylla/cassandra-rackdc.1.properties
        target: /etc/scylla/cassandra-rackdc.properties
      - type: bind
        source: ./scylla/scylla.yaml
        target: /etc/scylla/scylla.yaml
    networks:
      public:
        ipv4_address: 192.168.100.12

  dc1_node_3:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    privileged: true
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - type: bind
        source: ./scylla/cassandra-rackdc.1.properties
        target: /etc/scylla/cassandra-rackdc.properties
      - type: bind
        source: ./scylla/scylla.yaml
        target: /etc/scylla/scylla.yaml
    networks:
      public:
        ipv4_address: 192.168.100.13

  dc2_node_1:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    privileged: true
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - type: bind
        source: ./scylla/cassandra-rackdc.2.properties
        target: /etc/scylla/cassandra-rackdc.properties
      - type: bind
        source: ./scylla/scylla.yaml
        target: /etc/scylla/scylla.yaml
    networks:
      public:
        ipv4_address: 192.168.100.21

  dc2_node_2:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    privileged: true
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - type: bind
        source: ./scylla/cassandra-rackdc.2.properties
        target: /etc/scylla/cassandra-rackdc.properties
      - type: bind
        source: ./scylla/scylla.yaml
        target: /etc/scylla/scylla.yaml
    networks:
      public:
        ipv4_address: 192.168.100.22

  dc2_node_3:
    image: scylladb/scylla-ssh:${SCYLLA_VERSION}
    privileged: true
    command: --smp 2 --seeds 192.168.100.11,192.168.100.21
    environment:
      AWS_ACCESS_KEY_ID: ${MINIO_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - type: bind
        source: ./scylla/cassandra-rackdc.2.properties
        target: /etc/scylla/cassandra-rackdc.properties
      - type: bind
        source: ./scylla/scylla.yaml
        target: /etc/scylla/scylla.yaml
    networks:
      public:
        ipv4_address: 192.168.100.23

  scylla-manager-db:
    image: scylladb/scylla:${SCYLLA_VERSION}
    command: --smp 1 --api-address 0.0.0.0
    networks:
      public:
        ipv4_address: 192.168.100.100

  prometheus:
    image: prom/prometheus
    volumes:
      - type: bind
        source: ./prometheus/prometheus.yaml
        target: /etc/prometheus/prometheus.yml
    ports:
      - 9090
    network_mode: host

  minio:
    image: minio/minio
    user: ${MINIO_USER}
    command: server /data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - type: bind
        source: ${MINIO_DATA_DIR}
        target: /data
    ports:
      - 9000
    networks:
      public:
        ipv4_address: 192.168.100.99

networks:
  public:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
