http: 127.0.0.1:9090

database:
  hosts:
    - 172.16.1.10
    - 172.16.1.20
  migrate_dir: schema/cql

clusters:
  - uuid: a3f1b32b-ed5b-438d-81a7-c82eb7bde800
    hosts:
      - 172.16.1.10
      - 172.16.1.20
    shard_count: 2
    murmur3_partitioner_ignore_msb_bits: 12
